export function assertError(message, fun) {
    let error;
    try {
        fun();
        throw new Error(message);
    }
    catch (err) {
        error = err;
    }
    return error;
}
//# sourceMappingURL=assert-error.js.map